---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  annotations:
    field.cattle.io/description: github generic-example
  name: generic-example
  namespace: fleet-default
spec:
  branch: main
  paths:
  - /security/openbao
  pollingInterval: 300s
  repo: https://github.com/suse-janguyen/fleet-awesome
  targets:
  - name: openbao
    clusterGroupSelector:
      matchLabels:
        name: security

###

