---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  annotations:
    field.cattle.io/description: github generic-example
  name: tf-fleet
  namespace: fleet-default
spec:
  branch: main
  paths:
  - /security/openbao
  pollingInterval: 300s
  repo: https://github.com/your-username/yourfork-fleet-awesome
  # targets:
  # - name: openbao
  #   clusterGroupSelector:
  #     matchLabels:
  #       rancher-localpath-prov: enabled