---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    cni:
      chainingMode: "none"
    operator:
      replicas: 1
    bgpControlPlane:
      enabled: true
    externalIPs: 
      enabled: true
    gatewayAPI:
      enabled: true

###
